definitions:
  dto.AddUserDto:
    properties:
      email:
        type: string
      password:
        type: string
      phone:
        type: string
      username:
        type: string
    required:
    - email
    - password
    - phone
    - username
    type: object
info:
  contact: {}
  description: 使用gin+vue进行极速开发的全栈开发基础平台
  title: GoGoFly Swagger API接口文档
  version: v1.0.1
paths:
  /api/v1/auth/user/addUser:
    post:
      consumes:
      - application/json
      description: 用户注册详细描述
      parameters:
      - description: username
        in: body
        name: username
        required: true
        schema:
          $ref: '#/definitions/dto.AddUserDto'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 添加用户
      tags:
      - 用户模块
  /api/v1/auth/user/getUserById/{id}:
    get:
      consumes:
      - application/json
      description: 获取用户详情描述
      parameters:
      - description: username
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取用户详情
      tags:
      - 用户模块
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
